# Generated by Django 4.0 on 2022-01-06 19:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='calculated',
        ),
        migrations.DeleteModel(
            name='input',
        ),
        migrations.DeleteModel(
            name='weights',
        ),
    ]
