# Generated by Django 4.0 on 2022-01-08 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Exercise', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='weights',
            name='category',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
