# Generated by Django 4.0 on 2022-01-08 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Exercise', '0002_weights_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='inputweights',
            name='percentage',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
