# Generated by Django 4.0 on 2022-01-11 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Exercise', '0004_inputweights_calories_ate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inputweights',
            name='calories_ate',
        ),
    ]
